### PR TITLE
Redis keys command is evil

### PR DESCRIPTION
**Pull request by felipeclopes**
Removed keys command that are used in Superworker execution.

This should improve performance as well as start the support to redis clusters.

### CODE REVIEW

**Comment by felipeclopes** [comment]
bump!

**Comment by felipeclopes** [comment]
No response on this?

**Comment by tombenner** [comment]
Great, this is an important improvement! I'll include an upgrade note in the README, and may also rename `#{redis_prefix}:#{superjob_id}:members` to `#{redis_prefix}:#{superjob_id}:subjob_keys` for clarity's sake. Many thanks!

**Comment by felipeclopes** [comment]
Welcome! Thank you for supporting this awesome gem.

**Pull request merged**
